[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://ibvap-intelligent-border-video-analytics-3tr5.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "https://ibvap-intelligent-border-video-analytics-3tr5.onrender.com/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

